language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/build/

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

virtualenv:
  system_site_packages: true

before_install:
  - export filename="shellcheck_0.3.7-5_amd64.deb"
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/$filename"
  - sudo dpkg -i "$filename"
  - pip install pip --upgrade

install:
  - pip install pylint
  - pip install bashate
  - pip install flake8

script:
  - python .travis/build.py
