sudo: false
language: python
python: 2.7

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/build/

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

virtualenv:
  system_site_packages: true

before_install:
  - wget "$shellcheck_url$filename"
  - sudo dpkg -i "$shellcheck_filename"
  - pip install pip --upgrade

install:
  - pip install pep8
  - pip install pylint
  - pip install bashate
  - pip install flake8

script:
  - python .travis/build.py
