language: python
python: 2.7

sudo: true 
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  edge: true
  directories:
    - $HOME/.build
    - $HOME/.cache/pip

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
  - pip install pip --upgrade
  - sudo apt-get install tidy


env:
  matrix:
    - TOXENV=python
    - TOXENV=bash
    - TOXENV=html

install:
  - pip install tox
  - pip install pep8
  - pip install pylint
  - pip install bashate
  - pip install flake8

script:
  - tox
