language: python
python: 2.7

virtualenv:
  system_site_packages: true

before_install:
  - pip install pip --upgrade

install:
  - pip install pylint

script:
  - for scriptura in $(find solutii | grep ".py$"); do pylint $scriptura; done
